from enum import Enum

class Platform(Enum):
    PlayStation = "PlayStation"
    PlayStation_2 = "PlayStation 2"
    Dreamcast = "Dreamcast"
    Nintendo_64 = "Nintendo 64"
    Game_Boy = "Game Boy"
    Game_Boy_Color = "Game Boy Color"
    Game_Boy_Advance = "Game Boy Advance"
    Xbox = "Xbox"
    GameCube = "GameCube"
    SNES = "SNES"
    Mega_Drive = "Genesis"
    SEGA_CD = "SEGA CD"
    SEGA_32X = "SEGA 32X"
    NES = "NES"
    SEGA_SATURN = "SEGA Saturn"
    SEGA_Master_System = "SEGA Master System"
    Nintendo_DS = "Nintendo DS"
    PSP = "PSP"
    Xbox_360 = "Xbox 360"
    PlayStation_3 = "PlayStation 3"
    Wii = "Wii"
    Nindendo_DSi = "Nintendo DSi"
    Nintendo_3DS = "Nintendo 3DS"
    PS_Vita = "PS Vita"
    Wii_U = "Wii U"
    PlayStation_4 = "PlayStation 4"
    Xbox_One = "Xbox One"
    New_Nintendo_3DS = "New Nintendo 3DS"
    Nintendo_Switch = "Nintendo Switch"
    Xbox_Series = "Xbox Series"
    PlayStation_5 = "PlayStation 5"